Exercise 17
Jurjens comment:
- You use throw(), which is deprecated in C++11 as well as C++17, and
boils down to the same as noexcept. The idea was to not use it, and
mimick its behaviour, as you did quite well with asaThrowList.
Also, you include showexcepts.hh (sic), which isn't there.


Using 'throw 1', the code works fine. When changing this to 'throw 1.0', we get
the following output:

terminate called after throwing an instance of 'std::bad_exception'
  what():  std::bad_exception
Aborted (core dumped)

When we use the member function asNoexcept however, we get the following output:

terminate called after throwing an instance of 'double'
Aborted (core dumped)
